#!/bin/bash

#home_device="Living Room mini"
home_device="Kitchen"

#cast-linux-amd64 --name "$home_device" media play http://stream.radioparadise.com:80/aac-320
cast-linux-amd64 --name "$home_device" media play http://stream.radioparadise.com:80/flacm
