#!/bin/bash

#home_device="Living Room mini"
home_device="Kitchen home"

touch ~/.tr

if [[ -f ~/.lbc ]]; then rm ~/.lbc & touch ~/.tr
fi

/home/swipe/bin/cast-linux-amd64 --name "$home_device" media play http://radio.talksport.com/stream
