#!/bin/bash
# exit if another instance of this script is running
for pid in $(pidof -x `basename $0`); do
    
    if [ $pid != $$ ]
        then
        echo " : $0 : Process is running with PID $pid"
        exit 1
    fi
done
