#!/bin/bash
#Checks kernel.org for a new linux 4.4 lts version and runs update.sh to update the PKGBUILD

newver="$(curl -sSf https://www.kernel.org/releases.json | jq -r '.releases[].version' | grep '^4\.4\.')"

#Get current package version from PKGBUILD file
curver=$(awk '/pkgver=/ {print substr($0,8)}' /home/swipe/.cache/pacaur/linux-lts44/PKGBUILD)


if [ "$newver" != "$curver" ] ;
then
    DISPLAY=:0 notify-send -t 100000 "New lts44 kernel available!" "Version $newver is now available and PKGBUILD updated" &
    /home/swipe/.cache/pacaur/linux-lts44/update.sh
fi


