#!/bin/sh
rsync -av --delete /home/swipe --exclude-from=/home/swipe/bin/exclude swipe@dell-i7:/home/swipe/backups/nuc
#rsync -av --delete /home/swipe --exclude-from=/home/swipe/bin/exclude swipe@:/laptop:/home/swipe/backups/nuc
