#!/bin/bash

confirm() {
    # call with a prompt string or use a default
    read -r -p "${1:-Are you sure? [y/N]} " response
    case "$response" in
        [yY][eE][sS]|[yY]) 
            true
            ;;
        *)
            false
            exit 1
            ;;
    esac
}


confirm "Are you sure you want to copy ""$1"" to dell-i7/~Videos [y/N]?"

scp /home/swipe/Downloads/$1 swipe@dell-i7:~/Videos
