#!/bin/bash

# Pass input variable $1 to volume and write $1 to volume value in mute_home on line 10

google_home="Kitchen"
#google_home="Bedroom mini"

/home/swipe/bin/cast-linux-amd64 --name "$google_home" volume $1 && sed -i -e "10s/\(volume \).*/\1$1/" ~/bin/mute_home 
