#!/bin/bash

mute () { "$HOME/bin/mute_radiotray-ng" -m /usr/bin/radiotray-ng && rename_xmuted; }
unmute () { "$HOME/bin/mute_radiotray-ng" -u /usr/bin/radiotray-ng && rename_muted; }
# high_vol () { "$HOME/bin/mute_radiotray-ng" -h /usr/bin/radiotray-ng; }
# low_vol () { "$HOME/bin/mute_radiotray-ng" -l /usr/bin/radiotray-ng; }
# peep () { sleep 0.75; }
rename_xmuted () { if [ -f "$HOME/.conky/xmuted.png" ]; then { mv "$HOME/.conky/xmuted.png" "$HOME/.conky/muted.png"; } fi }
rename_muted () { if [ -f "$HOME/.conky/muted.png" ]; then { mv "$HOME/.conky/muted.png" "$HOME/.conky/xmuted.png"; } fi }
lbc () { qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.play_station Imported 'LBC UK' ; sleep 3  ;  ~/.conky/conkyradiotray-ng/onair; }
radio3 () { qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.play_station BBC 'Radio 3'; sleep 3 ; ~/.conky/conkyradiotray-ng/onair; }
classicfm () { qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.play_station Classical 'Classic FM' ; }

# Clean up any obsolete .conkytimer files
rm ~/.conkytimer

# Conky countdown timer
conkytimer()
{
trap "rm ~/.conkytimer" INT

sec=$1
millisecondsToseonds=$(( $1/1000 ))

for (( i = 0; i < $sec; i++ )); do
        # write remaining sec to file
        timer=$((sec-i))
        display="                           ${timer}"
        echo "$display" > ~/.conkytimer
        # wait 1sec
        sleep 1
done

rm ~/.conkytimer
}


# check if time is between top of the hour and 6 minutes
check_top_of_the_hour()
{  
   # Get current time in minutes
   currenttime=$(date +%M)
   if [[ "$currenttime" > "00" ]] && [[ "$currenttime" < "07" ]]; then
        
        declare -i adlength=30
        
        mute

        qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 0
        
        #~/.conky/conkytimer "$adlength" &
        
        conkytimer "$adlength"
          
        #sleep "$adlength"
        
        unmute

        qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 60
    
        exit
   fi
}

check_top_of_the_hour

#mute

#qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 0

#radio3
classicfm

get_adbreak_length() 
{

# Get stream metadata
ffprobe http://media-ice.musicradio.com:80/LBCUK &> "$HOME/stream.txt"

# Cut six digit adbreak length from metadata file
adbreaklength=$(printf '%s' | awk -v RS='[[:blank:]]' '/^ADBREAK_LENGTH_/' "$HOME/stream.txt" | cut -c16-21)

#Remove any leading 0 digits
adbreaklength=$((10#$adbreaklength + 1))

# Set as integer and convert from ms to seconds
declare -i ms=$adbreaklength
declare -i value=("$ms"/1000)

echo "$value"

}


seconds=$(get_adbreak_length)

until [ "$seconds" -gt 0 ]
do 
    get_adbreak_length
    seconds=$(get_adbreak_length)
    sleep 5
done

#echo "$seconds"

#~/.conky/conkytimer $seconds &

conkytimer $seconds

#sleep "$seconds"

#unmute

lbc ; unmute

#qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 60
