#!/bin/sh
# Usage: ./toggle_mute3 X X X X X  (where X is no of seconds to mute for)

mute () { "$HOME/bin/mute_radiotray-ng" -m /usr/bin/radiotray-ng && mv ~/.conky/xmuted.png ~/.conky/muted.png; }
unmute () { "$HOME/bin/mute_radiotray-ng" -u /usr/bin/radiotray-ng && mv ~/.conky/muted.png ~/.conky/xmuted.png; }
high_vol () { "$HOME/bin/mute_radiotray-ng" -h /usr/bin/radiotray-ng; }
low_vol () { "$HOME/bin/mute_radiotray-ng" -l /usr/bin/radiotray-ng; }
peep () { sleep 0.75; }

mute
#mv ~/.conky/xmuted.png ~/.conky/muted.png
qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 0
sleep "$1"

low_vol && unmute && peep && mute
sleep "$2"

low_vol && unmute && peep && mute
sleep "$3"

low_vol && unmute && peep && mute
sleep "$4"

low_vol && unmute && peep && mute
sleep "$5"

high_vol && unmute
#mv ~/.conky/muted.png ~/.conky/xmuted.png
qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 60
