#!/bin/sh
mute="$HOME/bin/mute_radiotray -m /usr/bin/python2 /usr/bin/radiotray"
unmute="$HOME/bin/mute_radiotray -u /usr/bin/python2 /usr/bin/radiotray"
high_vol="$HOME/bin/mute_radiotray -h /usr/bin/python2 /usr/bin/radiotray"
low_vol="$HOME/bin/mute_radiotray -l /usr/bin/python2 /usr/bin/radiotray"
peep="sleep 0.75"

eval "$mute"
qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 0
sleep "$1"

eval "$low_vol" && eval "$unmute" && eval "$peep" && eval "$mute"
sleep "$2"

eval "$low_vol" && eval "$unmute" && eval "$peep" && eval "$mute"
sleep "$3"

eval "$low_vol" && eval "$unmute" && eval "$peep" && eval "$mute"
sleep "$4"

eval "$low_vol" && eval "$unmute" && eval "$peep" && eval "$mute"
sleep "$5"

eval "$high_vol" && eval "$unmute"
qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 60
